=== monarc-project/monarc-objects/threats-schemas.json
{
    "$schema": "http://json-schema.org/schema#",
    "additionalProperties": false,
    "id": "",
    "properties": {
        "authors": {
            "items": {
                "type": "string"
            },
            "type": "array",
            "uniqueItems": true
        },
        "uuid": {
            "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
            "type": "string"
        },
        "code": {
            "type": "string"
        },
        "label": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "c": {
            "default": 0,
            "type": "integer"
        },
        "i": {
            "default": 0,
            "type": "integer"
        },
        "a": {
            "default": 0,
            "type": "integer"
        },
        "theme": {
            "type": "string"
        },
        "language": {
            "default": "EN",
            "oneOf": [
                {
                    "pattern": "^[A-Z]{2}$",
                    "type": "string"
                }
            ],
            "type": "string"
        }
    },
    "required": [
        "uuid",
        "code",
        "label"
    ],
    "title": "Validator for threats used in MONARC",
    "type": "object"
}

=== monarc-project/monarc-objects/threats/b402d5c9-4576-11e9-9173-0800277f0571_DE.json
{"a": 0, "c": 1, "code": "MDA12", "description": "\u00dcbernahme von elektronischen Informationstr\u00e4gern (Festplatten, Disketten, Speicherkassetten, USB-Schl\u00fcssel, ZIP-Disketten, externen Festplatten usw.) oder von Papier (Listen, unvollst\u00e4ndige Textausgaben, Nachrichten usw.), die zum Recycling bestimmt sind", "i": 0, "label": "\u00dcbernahme recycelter oder ausgemusterter datentr\u00e4ger", "language": "DE", "theme": "Infragestellung von Informationen", "uuid": "b402d5c9-4576-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/threats/b402d60a-4576-11e9-9173-0800277f0571_NL.json
{"a": 1, "c": 0, "code": "MDA25", "description": "Gebrek aan beheersing van het systeem waardoor iedere upgrade of evolutie onmogelijk wordt", "i": 0, "label": "Aantasting van de onderhoudbaarheid van het informatiesysteem", "language": "NL", "theme": "Technische mankementen", "uuid": "b402d60a-4576-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/threats/b402d530-4576-11e9-9173-0800277f0571_FR.json
{"a": 1, "c": 1, "code": "MD14", "description": "Personne se faisant passer pour une autre de mani\u00e8re \u00e0 utiliser ces privil\u00e8ges d'acc\u00e8s au syst\u00e8me d'information, d\u00e9sinformer le destinataire, r\u00e9aliser une fraude\u2026", "i": 1, "label": "Usurpation de droits", "language": "FR", "theme": "Compromission des fonctions", "uuid": "b402d530-4576-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/threats/b402d688-4576-11e9-9173-0800277f0571_FR.json
{"a": 1, "c": 0, "code": "ME18", "description": "Tout \u00e9v\u00e8nement environnemental pouvant affecter physiquement les locaux de mani\u00e8re \u00e0 les rendre inutilisable.", "i": 1, "label": "Sinistre environnemental (Incendie, eau, poussi\u00e8re, salet\u00e9, etc.)", "language": "FR", "theme": "Sinistres physiques", "uuid": "b402d688-4576-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/threats/b402d668-4576-11e9-9173-0800277f0571_FR.json
{"a": 1, "c": 0, "code": "ME15", "description": "Perturbation, arr\u00eat ou mauvais dimensionnement des services de t\u00e9l\u00e9communication (t\u00e9l\u00e9phone, acc\u00e8s Internet, r\u00e9seau Internet).", "i": 0, "label": "Perte des moyens de t\u00e9l\u00e9communication", "language": "FR", "theme": "Perte de services essentiels", "uuid": "b402d668-4576-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/threats/b402d584-4576-11e9-9173-0800277f0571_NL.json
{"a": 0, "c": 0, "code": "MD23", "description": "Persoon die zich toegang verschaft tot de communicatiemiddelen van het informatiesysteem en die de overdracht van gegevens wijzigt (door onderschepping, inlassing, vernietiging ...) of een beroep doet op die toegangsmogelijkheden tot hij een geautoriseerde toegang vindt.", "i": 1, "label": "Wijziging van de gegevens", "language": "NL", "theme": "Onrechtmatige acties", "uuid": "b402d584-4576-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/threats/b402d599-4576-11e9-9173-0800277f0571_FR.json
{"a": 0, "c": 1, "code": "MD26", "description": "Personne effectuant un traitement d\u2019information non autoris\u00e9 par la l\u00e9gislation ou un r\u00e8glement.", "i": 1, "label": "Traitement illicite des donn\u00e9es", "language": "FR", "theme": "Actions illicites", "uuid": "b402d599-4576-11e9-9173-0800277f0571"}
