=== monarc-project/monarc-objects/threats-schema.json
{
    "$id": "https://objects.monarc.lu/schema/def/9b9e44b1-a943-4f95-b0c3-df1015063a10",
    "title": "Validator for threats used in MONARC",
    "$schema": "http://json-schema.org/schema#",
    "additionalProperties": false,
    "properties": {
        "a": {
            "default": false,
            "type": "boolean"
        },
        "authors": {
            "items": {
                "type": "string"
            },
            "type": "array",
            "uniqueItems": true
        },
        "c": {
            "default": false,
            "type": "boolean"
        },
        "code": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "i": {
            "default": false,
            "type": "boolean"
        },
        "label": {
            "type": "string"
        },
        "language": {
            "default": "EN",
            "oneOf": [
                {
                    "pattern": "^[A-Z]{2}$",
                    "type": "string"
                }
            ],
            "type": "string"
        },
        "theme": {
            "type": "string"
        },
        "uuid": {
            "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
            "type": "string"
        }
    },
    "required": [
        "uuid",
        "code",
        "label"
    ],
    "type": "object"
}

=== monarc-project/monarc-objects/threats/b402d5d5-4576-11e9-9173-0800277f0571_FR.json
{"a": true, "c": true, "code": "MDA13", "description": "Logiciel non d\u00e9sir\u00e9 executant des op\u00e9rations cherchant \u00e0 nuire \u00e0 l'organisme.", "i": true, "label": "Infection par un malware", "language": "FR", "theme": "Compromission des informations", "uuid": "b402d5d5-4576-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/threats/b402d557-4576-11e9-9173-0800277f0571_EN.json
{"a": false, "c": true, "code": "MD15", "description": "Someone connected to communication equipment or media or located inside the transmission coverage boundaries of a communication.", "i": false, "label": "Eavesdropping", "language": "EN", "theme": "Compromise of functions", "uuid": "b402d557-4576-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/threats/b402d530-4576-11e9-9173-0800277f0571_DE.json
{"a": true, "c": true, "code": "MD14", "description": "Jemand gibt sich als jemand anderes aus, um sich mit dessen Zugriffsprivilegien Zugang zum IT-System zu verschaffen, den Empf\u00e4nger falsch zu informieren, eine betr\u00fcgerische Tat auszuf\u00fchren usw.\n", "i": true, "label": "Rechtsanmassung", "language": "DE", "theme": "Infragestellung von Funktionen", "uuid": "b402d530-4576-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/threats/b402d5af-4576-11e9-9173-0800277f0571_DE.json
{"a": true, "c": true, "code": "MD36", "description": "Die Datentr\u00e4ger, Dokumente oder Betriebsmittel sind f\u00fcr Fremde, entweder intern oder extern, zug\u00e4nglich. Sie k\u00f6nnen zerst\u00f6rt oder gestohlen werden\n", "i": false, "label": "Entwenden oder Zerst\u00f6ren von Speichermedien, Dokumenten oder Datentr\u00e4ger", "language": "DE", "theme": "Infragestellung von Informationen", "uuid": "b402d5af-4576-11e9-9173-0800277f0571"}
