=== monarc-project/monarc-objects/vulnerabilities-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "additionalProperties": false,
    "id": "",
    "properties": {
        "authors": {
            "items": {
                "type": "string"
            },
            "type": "array",
            "uniqueItems": true
        },
        "code": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "label": {
            "type": "string"
        },
        "language": {
            "default": "EN",
            "oneOf": [
                {
                    "pattern": "^[A-Z]{2}$",
                    "type": "string"
                }
            ],
            "type": "string"
        },
        "mode": {
            "default": 0,
            "type": "integer"
        },
        "status": {
            "default": 0,
            "type": "integer"
        },
        "uuid": {
            "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
            "type": "string"
        }
    },
    "required": [
        "uuid",
        "code",
        "label"
    ],
    "title": "Validator for vulnerabilities used in MONARC",
    "type": "object"
}

=== monarc-project/monarc-objects/vulnerabilities/69fc1c92-4591-11e9-9173-0800277f0571_FR.json
{"code": "602", "description": "", "label": "Absence de r\u00e8gles traitant des conditions d'usage des infrastructures de traitement de l'information (interdiction dans les locaux h\u00e9bergeant du mat\u00e9riel informatique de consommation de tabac, de boisson, d'aliments)", "language": "FR", "uuid": "69fc1c92-4591-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/vulnerabilities/69fc0421-4591-11e9-9173-0800277f0571_FR.json
{"code": "1165", "description": "Les utilisateurs ont-ils \u00e9t\u00e9 sensibilis\u00e9s \u00e0 la s\u00e9curit\u00e9 de l'information ?\nDes consignes unitaires ont-elles \u00e9t\u00e9 fournies par email, consigne interne, circulaire interne ... ?", "label": "Les utilisateurs ne sont pas sensibilis\u00e9s \u00e0 la s\u00e9curit\u00e9 de l'information", "language": "FR", "uuid": "69fc0421-4591-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/vulnerabilities/69fc05bf-4591-11e9-9173-0800277f0571_DE.json
{"code": "1214", "description": "Werden die Rechte f\u00fcr den physischen Zugang zu sensiblen R\u00e4umlichkeiten regelm\u00e4\u00dfig \u00fcberpr\u00fcft?\nBenutzer? Administratoren?", "label": "Keine regelm\u00e4\u00dfige Kontrolle der Genehmigungen f\u00fcr den physischen Zugang", "language": "DE", "uuid": "69fc05bf-4591-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/vulnerabilities/69fc0536-4591-11e9-9173-0800277f0571_DE.json
{"code": "1179", "description": "Besteht die Gefahr von Umweltkatastrophen (Wasser, Hochwasser, Feuer, Staub, Leitungen, starke W\u00e4rmeentwicklung usw.)?\nGibt es Brandschutzt\u00fcren?\nGibt es Brandmelder? Feuerl\u00f6scher?", "label": "Die R\u00e4umlichkeiten sind nicht gesichert bzw. k\u00f6nnen von fremden Personen betreten werden.", "language": "DE", "uuid": "69fc0536-4591-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/vulnerabilities/69fc1a27-4591-11e9-9173-0800277f0571_FR.json
{"code": "530", "description": "", "label": "Absence de consignes de bon usage des ressources informatiques afin d'\u00e9viter des comportements conduisant \u00e0 la saturation des espaces de stockage ou des ressources de traitement", "language": "FR", "uuid": "69fc1a27-4591-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/vulnerabilities/69fc166f-4591-11e9-9173-0800277f0571_DE.json
{"code": "41", "description": "Werden die Administratorkonten von mehreren Personen genutzt?\nSind die Administratoren immer mit ihrem Admin-Konto eingeloogt?\nIst das generische Konto \"Admin\" deaktiviert?", "label": "Fehlende Verwaltung der Zugriffsprivilegien der einzelnen Profile (Administratoren, Anwender, G\u00e4ste usw.)", "language": "DE", "uuid": "69fc166f-4591-11e9-9173-0800277f0571"}

=== monarc-project/monarc-objects/vulnerabilities/69fc05d3-4591-11e9-9173-0800277f0571_FR.json
{"code": "1216", "description": "Est-ce que les personnes normalement non autoris\u00e9es sont sous surveillance lors d'intervention exceptionnelle (internes ou externes) ?", "label": "Absence de vigilance lors d'une intervention d\u2019un tiers (fournisseur, femme de m\u00e9nage, etc.)", "language": "FR", "uuid": "69fc05d3-4591-11e9-9173-0800277f0571"}
